# Generated by Django 6.1.1 on 2026-09-17 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('grade_level', models.CharField(help_text="Ex.: '8º ano', '2º ano EM'", max_length=50)),
                ('study_time_available', models.PositiveIntegerField(default=30, help_text='Minutos disponíveis por dia para estudo')),
                ('learning_preferences', models.JSONField(blank=True, default=dict, help_text="Ex.: {'formato_preferido': 'exercicios_praticos', 'melhor_horario': 'manha'}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
