# Generated by Django 6.1.1 on 2026-09-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='matricula',
            field=models.CharField(blank=True, help_text='Identificador de matrícula, opcional — usado pelo app `pedagogico` (boletim/frequência) como chave alternativa quando o export precisa evitar nome/username (LGPD). O User continua sendo a identidade real para login e permissões; isto é só um campo extra.', max_length=20, null=True, unique=True),
        ),
    ]
