# Generated by Django 6.1.1 on 2026-09-22 00:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimestre', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('nota', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_nota', to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_nota', to='subjects.subject')),
            ],
            options={
                'indexes': [models.Index(fields=['aluno', 'bimestre'], name='pedagogico__aluno_i_bbb04c_idx')],
                'unique_together': {('aluno', 'disciplina', 'bimestre')},
            },
        ),
        migrations.CreateModel(
            name='ParecerPedagogico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimestre', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('causa_raiz', models.TextField()),
                ('acao_recomendada', models.TextField()),
                ('aprovado_pelo_professor', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='pareceres_pedagogicos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('aluno', 'bimestre')},
            },
        ),
        migrations.CreateModel(
            name='RegistroFrequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('bimestre', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('presente', models.BooleanField(default=True)),
                ('aluno', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='registros_frequencia', to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_frequencia', to='subjects.subject')),
            ],
            options={
                'indexes': [models.Index(fields=['aluno', 'disciplina', 'bimestre'], name='pedagogico__aluno_i_7f3e5b_idx')],
                'unique_together': {('aluno', 'disciplina', 'data')},
            },
        ),
    ]
