# Generated by Django 5.2.17 on 2026-09-20 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyactivity',
            options={'ordering': ['study_plan', 'order'], 'verbose_name_plural': 'Study Activities'},
        ),
    ]
