# Generated by Django 6.1.1 on 2026-09-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, help_text='6 a 9 para Fundamental II; 1 a 3 para Ensino Médio.', null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='stage',
            field=models.CharField(blank=True, choices=[('fundamental_ii', 'Ensino Fundamental II'), ('ensino_medio', 'Ensino Médio')], max_length=20),
        ),
    ]
